### PR TITLE
WIP -- feat: add GCS gateway support

### PR DESCRIPTION
**Pull request by shadinaif**
Add proper support for GCS `gsc` gateway

### CODE REVIEW

**Comment by regisb** [comment]
This is an interesting feature. Please let me know when it is ready for review.
FYI I'd rather avoid GCS-specific configuration settings. But we'll discuss this when your PR is ready.

**Comment by shadinaif** [comment]
Thanks Régis, I'll ping you once we test on the GCP environment and verify it's working fine

**Comment by shadinaif** [comment]
Following up, it's being tested in a live staging server. We still have an issue to address. When it's fixed and works; I'll add the fix here too and set it as ready to review

**Comment by FahadKhalid210** [comment]
@shadinaif I was wondering if there have been any further updates or progress on addressing the remaining issue. When you have a moment, could you please provide an update?

**Comment by FahadKhalid210** [comment]
@shadinaif I wanted to follow up on my previous inquiry regarding any updates or progress on addressing the remaining issue. Your input on this matter is greatly appreciated. Looking forward to hearing from you when you have a moment.

**Comment by shadinaif** [comment]
Hi @FahadKhalid210 , I'll push the latest code soon, just for reference. But I'll close the PR after that. We faced an unresolvable issue with MinIO gateway, plus MinIO stopped supporting the gateway permanently. We fixed it with [a workaround](https://github.com/correlation-one/tutor-minio/pull/3) (a hack you can say). Now we're moving out of MinIO to use GCS directly

**Comment by FahadKhalid210** [comment]
@shadinaif Thanks for the update! Can we go ahead and close this PR now?

**Pull request closed without merging**
