### PR TITLE
Minio domain

### PR DESCRIPTION
**Pull request by insad**
For getting video upload with presigned url's to work (the old boto based code in https://github.com/openedx/edx-platform/blob/master/cms/djangoapps/contentstore/views/videos.py) to MinIO, it is necessary to define the environment variable MINIO_DOMAIN (see https://docs.min.io/docs/minio-server-configuration-guide.html - completely at the bottom). 

This variable must be set (initially) to {{ LMS_HOST }}, in this way MinIO can extract the bucket name "files" from the presigned upload url, which is of the form:

```https://files.lmshost.tld:443/videos/07613d52-4cda-4cbf-bf7d-4a64da41e7d0?Signature=dogBMJ%2Bc6umxbvOPJ5Sw4V2qFwo%3D&Expires=1659073179&AWSAccessKeyId=openedx&x-amz-meta-client_video_id=testvideo.mp4&x-amz-meta-course_key=course-1234```

The bucket name for MinIO is  (+.).lmshost.tld - in this case "files".

Thus, we need to make a bucket called "files" in MinIO, I changed the (undocument) parameter VIDEO_UPLOAD_BUCKET_NAME to "files" for that. A bit weird, but Amazon S3 figures out the bucket name from the (for each bucket unique) url, while our MinIO runs under a fixed url (Amazon uses virtual style bucket names, where the name is part of the url).

The presigned upload url as above is being generated, setting the following parameters in a plugin:

```
hooks.Filters.ENV_PATCHES.add_item(
    (
        "openedx-cms-common-settings",
        "FEATURES['ENABLE_VIDEO_UPLOAD_PIPELINE'] = True"
    )
)

hooks.Filters.ENV_PATCHES.add_item(
    (
        "openedx-cms-common-settings",
        "VIDEO_UPLOAD_PIPELINE['VEM_S3_BUCKET'] = 'files'"
    )
)

hooks.Filters.ENV_PATCHES.add_item(
    (
        "openedx-cms-common-settings",
        "VIDEO_UPLOAD_PIPELINE['ROOT_PATH'] = 'videos'"
    )
)
```

With a small patch in videos.py - adding the host url to the connections parameters:

```
        params = {
            'host': 'lmshost.tld',
            'aws_access_key_id': settings.AWS_ACCESS_KEY_ID,
            'aws_secret_access_key': settings.AWS_SECRET_ACCESS_KEY
        }
```
and many sleepless nights (must configure the frontend proxy to rewrite both x-amz-meta-* query parameters as unescaped header parameters), I got video upload to MiniIO working in Studio:

image

image

### CODE REVIEW

**Comment by insad** [comment]
Will make some changes still...

**Comment by regisb** [comment]
Hi @insad,
This looks very promising. Personally I I had tried to enable video uploads a long time ago, without success. However I wasn't aware of the MINIO_DOMAIN environment variable.
I'm not going to be available for a couple of weeks so I won't be able to test this pr. @BbrSofiane, if you are available I'm letting you merge this.

**Comment by insad** [comment]
I will post later polished plugin settings and instructions how to configure at least apache2 for getting the upload to work. The important part to add for apache2 is (unescaping the x-amz-meta query parameters and setting them as head parameters):

    RewriteEngine On

    RewriteMap ue int:unescape

    RewriteCond %{QUERY_STRING} (?:^|&)x-amz-meta-client_video_id=([^&]+)
    RewriteRule (.*) - [E=VIDEO_ID:${ue:%1}]
    RequestHeader set X-Amz-Meta-Client_video_id %{VIDEO_ID}e env=VIDEO_ID

    RewriteCond %{QUERY_STRING} (?:^|&)x-amz-meta-course_key=([^&]+)
    RewriteRule (.*) - [E=COURSE_KEY:${ue:%1}]
    RequestHeader set X-Amz-Meta-Course_key %{COURSE_KEY}e env=COURSE_KEY

**Comment by insad** [comment]
@regisb @BbrSofiane  I just posted step-by-step instructions on the forum to get video upload working:

https://discuss.openedx.org/t/getting-video-upload-to-minio-working-in-studio/7959

@regisb I wouldn't mind to make / publish an official tutor plugin for this under overhang.io, if you like the idea.

**Comment by insad** [comment]
UPDATE: setting MINIO_DOMAIN has as result, that the other assets (avatars, translations, images) can't be found anymore or are being uploaded to the wrong bucket 😤

I found the following two discussions:

https://github.com/minio/minio/blob/ce6c23a360090fee242b6ce1fd490c5035ad78c0/docs/config/README.md (under Domain)
and
https://docs.aws.amazon.com/AmazonS3/latest/userguide/RESTAPI.html

So Amazon is going to deprecate path-style requests (bucket name in path ... what's appearantly being used all over in Open edX), in favor of virtual-hosted style (bucket name as part of the endpoint domain).... what a mess... 

Closing this pull request until I find out a better solution...

**Comment by BbrSofiane** [comment]
Sounds good, @insad. I'll be ready to review it.

**Comment by insad** [comment]
Hi @BbrSofiane This patch is not needed anymore and will cause problems with the upload of other assets. Please take a look at https://discuss.openedx.org/t/getting-video-upload-to-minio-working-in-studio/7959/2 - only 2 extra lines needed in the video upload code and a correct proxy server configuration 😁
So please dismiss this pull request.

**Pull request closed without merging**
