### PR TITLE
fix: grades configurations

### LINKED ISSUE #43: Graded download issues
This is a duplicate of https://github.com/hastexo/tutor-contrib-s3/issues/77

Hi. I noticed a couple of issues related to GRADES_DOWNLOAD.
There's a section in the instructor tab of each course, where instructors can download grades in a CSV format.
Inside `lms/djangoapps/instructor_task/models.py`, where we create a `DjangoStorageReportStore`, it needs these values from the config, otherwise will fail:

- STORAGE_TYPE
- BUCKET
- ROOT_PATH
- CUSTOM_DOMAIN (if exists)

https://github.com/openedx/edx-platform/blob/f3f160f4f20f7bbde45fe0d48ac9626a694afb93/lms/djangoapps/instructor_task/models.py#L230-L242

Oddly, it's not reading them from `AWS_S3_` configs.

In the plugin, just a bucket_name and a location kwargs are overridden.

```python
GRADES_DOWNLOAD["STORAGE_KWARGS"] = {"location": GRADES_DOWNLOAD["STORAGE_KWARGS"]["location"].lstrip("/")}
GRADES_DOWNLOAD["STORAGE_KWARGS"]["bucket_name"] = "{{ S3_GRADE_BUCKET }}"
```

Note that I didn't use the plugin, but just used `GRADES_DOWNLOAD` config mentioned above and it didn't work. 
If this is a valid issue, I would like to work on it.

### PR DESCRIPTION
**Pull request by CodeWithEmad**
This will fix #43 and clean up the common settings patch and readme files.

### CODE REVIEW

**Comment by DawoudSheraz** [comment]
@FahadKhalid210 Please take a look at this, thanks.

**Comment by FahadKhalid210** [comment]
Hi @CodeWithEmad I've tested the **Generate Grade Report** with minio plugin enabled, and the reports are generated successfully without any issues. Could you please try this by enabling the plugin and let me know if you experience any issue? 
image

Minio Bucket:
image

**Comment by CodeWithEmad** [comment]
That's weird. There might be something with my setup. I'll try to reproduce it and will let you know.

**Comment by CodeWithEmad** [comment]
Hey @DawoudSheraz. I'm afraid not. I don't have access to that instance anymore. I'll close this one and will update you if something comes up.

**Pull request closed without merging**
